openapi: 3.0.0
info:
  title: openweathermap
  version: '1.0'
  description: 'Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format'
  contact:
    name: Support
    url: 'https://openweathermap.org/api'
    email: some_email@gmail.com
  termsOfService: 'https://openweathermap.org/terms'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
paths:
  /weather:
    get:
      summary: Weather
      tags:
        - Weather endpoints
      responses: {}
      operationId: get-weather
      security:
        - app_id: []
      parameters:
        - schema:
            type: string
          in: query
          name: q
          description: 'Use city name, state code or ISO 3166 country code. Example: "London"'
          required: true
        - schema:
            type: string
          in: query
          name: zip
          description: Zip code. Example "95050"
      description: 'Access current weather data for any location on Earth including over 200,000 cities.'
components:
  schemas: {}
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
  parameters:
    lon:
      name: lon
      in: query
      description: '**Longitude**. *Example: 139*. Longitude coordinate of the location of your interest. Must use with `lat`.'
      schema:
        type: string
tags:
  - name: Weather endpoints
